version: "3.5"

x-shared-config:
  base: &base
    command: /bin/bash
    image: opentelemetry/opentelemetry-ruby
    stdin_open: true
    tmpfs:
      - /tmp
    tty: true
    user: "1000:1000"
    volumes:
      - .:/app:cached
      - bundle:/bundle

services:
  api:
    <<: *base
    working_dir: /app/api

  app:
    <<: *base
    build:
      context: .
    working_dir: /app

  ex-instrumentation-concurrent-ruby:
    <<: *base
    working_dir: /app/instrumentations/concurrent_ruby/example

  ex-instrumentation-ethon:
    <<: *base
    working_dir: /app/instrumentations/ethon/example

  ex-instrumentation-excon:
    <<: *base
    working_dir: /app/instrumentations/excon/example

  ex-instrumentation-faraday:
    <<: *base
    working_dir: /app/instrumentations/faraday/example

  ex-instrumentation-net-http:
    <<: *base
    working_dir: /app/instrumentations/net_http/example

  ex-instrumentation-rack:
    <<: *base
    working_dir: /app/instrumentations/rack/example

  ex-instrumentation-redis:
    <<: *base
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    working_dir: /app/instrumentations/redis/example

  ex-instrumentation-restclient:
    <<: *base
    working_dir: /app/instrumentations/restclient/example

  ex-instrumentation-sidekiq:
    <<: *base
    working_dir: /app/instrumentations/sidekiq/example

  ex-instrumentation-sinatra:
    <<: *base
    command: ./start_server.sh
    working_dir: /app/instrumentations/sinatra/example

  ex-http:
    <<: *base
    command: ./start_server.sh
    working_dir: /app/examples/http

  redis:
    image: redis:5.0-alpine
    volumes:
      - redis_data:/data

  sdk:
    <<: *base
    working_dir: /app/sdk

volumes:
  bundle:
  redis_data:
