# Copyright 2019 OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

version: 2.1
executors:
  ruby25:
    docker:
      - image: "circleci/ruby:2.5-buster"
  ruby26:
    docker:
      - image: "circleci/ruby:2.6-buster"
  ruby27:
    docker:
      - image: "circleci/ruby:2.7-buster"
  jruby:
    docker:
      - image: "circleci/jruby:latest"
    environment:
      JRUBY_OPTS: "--debug"
  jruby92:
    docker:
      - image: "circleci/jruby:9.2.8-jre"
    environment:
      JRUBY_OPTS: "--debug"
commands:
  rake-test:
    steps:
      - checkout
      - run:
          name: Bundle (API)
          command: "cd api && gem install --no-document bundler && bundle install --jobs=3 --retry=3"
      - run:
          name: Bundle (SDK)
          command: "cd sdk && gem install --no-document bundler && bundle install --jobs=3 --retry=3"
      - run:
          name: Bundle (Jaeger)
          command: "cd exporters/jaeger && gem install --no-document bundler && bundle install --jobs=3 --retry=3"
      - run:
          name: CI (API)
          command: "cd api && bundle exec rake"
      - run:
          name: CI (SDK)
          command: "cd sdk && bundle exec rake"
      - run:
          name: CI (Jaeger)
          command: "cd exporters/jaeger && bundle exec rake"
  rake-test-appraisal:
    steps:
      - run:
          name: Bundle + CI (Instrumentations - Concurrent Ruby)
          command: |
            cd instrumentations/concurrent_ruby
            gem uninstall -aIx bundler
            gem install --no-document bundler -v '~> 2.0.2'
            bundle install --jobs=3 --retry=3
            bundle exec appraisal install
            bundle exec appraisal rake test
      - run:
          name: Bundle + CI (Instrumentations - ethon)
          command: |
            cd instrumentations/ethon
            gem uninstall -aIx bundler
            gem install --no-document bundler -v '~> 2.0.2'
            bundle install --jobs=3 --retry=3
            bundle exec appraisal install
            bundle exec appraisal rake test
      - run:
          name: Bundle + CI (Instrumentations - excon)
          command: |
            cd instrumentations/excon
            gem uninstall -aIx bundler
            gem install --no-document bundler -v '~> 2.0.2'
            bundle install --jobs=3 --retry=3
            bundle exec appraisal install
            bundle exec appraisal rake test
      - run:
          name: Bundle + CI (Instrumentations - Faraday)
          command: |
            cd instrumentations/faraday
            gem uninstall -aIx bundler
            gem install --no-document bundler -v '~> 2.0.2'
            bundle install --jobs=3 --retry=3
            bundle exec appraisal install
            bundle exec appraisal rake test
      - run:
          name: Bundle + CI (Instrumentations - Net::HTTP)
          command: |
            cd instrumentations/net_http
            gem uninstall -aIx bundler
            gem install --no-document bundler -v '~> 2.0.2'
            bundle install --jobs=3 --retry=3
            bundle exec rake test
      - run:
          name: Bundle + CI (Instrumentations - Rack)
          command: |
            cd instrumentations/rack
            gem uninstall -aIx bundler
            gem install --no-document bundler -v '~> 2.0.2'
            bundle install --jobs=3 --retry=3
            bundle exec appraisal install
            bundle exec appraisal rake test
      - run:
          name: Bundle + CI (Instrumentations - Redis)
          command: |
            cd instrumentations/redis
            gem uninstall -aIx bundler
            gem install --no-document bundler -v '~> 2.0.2'
            bundle install --jobs=3 --retry=3
            bundle exec appraisal install
            bundle exec appraisal rake test
      - run:
          name: Bundle + CI (Instrumentations - REST Client)
          command: |
            cd instrumentations/restclient
            gem uninstall -aIx bundler
            gem install --no-document bundler -v '~> 2.0.2'
            bundle install --jobs=3 --retry=3
            bundle exec appraisal install
            bundle exec appraisal rake test
      - run:
          name: Bundle + CI (Instrumentations - Sidekiq)
          command: |
            cd instrumentations/sidekiq
            gem uninstall -aIx bundler
            gem install --no-document bundler -v '~> 2.0.2'
            bundle install --jobs=3 --retry=3
            bundle exec appraisal install
            bundle exec appraisal rake test
      - run:
          name: Bundle + CI (Instrumentations - Sinatra)
          command: |
            cd instrumentations/sinatra
            gem uninstall -aIx bundler
            gem install --no-document bundler -v '~> 2.0.2'
            bundle install --jobs=3 --retry=3
            bundle exec appraisal install
            bundle exec appraisal rake test
  rake-release:
    steps:
      - checkout
      - run:
          name: Install rake
          command: "gem install --no-document rake"
      - run:
          name: Release
          command: "rake push_release"
jobs:
  test-ruby25:
    executor: ruby25
    steps:
      - rake-test
      - rake-test-appraisal
  test-ruby26:
    executor: ruby26
    steps:
      - rake-test
      - rake-test-appraisal
  test-ruby27:
    executor: ruby27
    steps:
      - rake-test
  test-jruby:
    executor: jruby
    steps:
      - rake-test
  test-jruby92:
    executor: jruby92
    steps:
      - rake-test
      - rake-test-appraisal
  release:
    executor: ruby26
    steps:
      - rake-release
      - rake-test-appraisal
workflows:
  version: 2
  builds:
    jobs:
      - test-ruby25:
          filters:
            tags:
              only: /^opentelemetry-.+\/v\d.*$/
      - test-ruby26:
          filters:
            tags:
              only: /^opentelemetry-.+\/v\d.*$/
      - test-ruby27:
          filters:
            tags:
              only: /^opentelemetry-.+\/v\d.*$/
      - test-jruby:
          filters:
            tags:
              only: /^opentelemetry-.+\/v\d.*$/
      - test-jruby92:
          filters:
            tags:
              only: /^opentelemetry-.+\/v\d.*$/
      - release:
          requires:
            - test-ruby25
            - test-ruby26
            - test-ruby27
            - test-jruby
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^opentelemetry-.+\/v\d.*$/
